export type {
	ComputedGetter,
	ComputedRef,
	ComputedSetter,
	DebuggerOptions,
	DeepReadonly,
	Ref,
	ToRefs,
	UnwrapNestedRefs,
	UnwrapRef,
	WritableComputedOptions,
	WritableComputedRef,
} from '@vue/reactivity';
export {
	customRef,
	isProxy,
	isReactive,
	isReadonly,
	isRef,
	computed as makeComputed,
	reactive as makeReactive,
	markRaw,
	readonly,
	ref,
	shallowReactive,
	shallowReadonly,
	shallowRef,
	toRaw,
	toRef,
	toRefs,
	triggerRef,
} from '@vue/reactivity';
